export const INITIAL_HOUSEHOLD = {
  id: 'hh_8829',
  head: 'Amina Bello',
  headRole: 'Family Caretaker', // Options: 'Pregnant Woman', 'New Mother', 'Family Caretaker'
  currency: '₦',
  monthlyBudgetCap: 25000,
  language: 'en', // 'en', 'ha' (Hausa), 'yo' (Yoruba), 'ig' (Igbo), 'sw' (Swahili)
  lastSyncTime: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  emergencyPhone: '+234 803 555 0192',
  clinicAnchor: 'Iru Comprehensive Primary Health Post, Lagos',
  members: [
    {
      id: 'mem_1',
      name: 'Amina Bello',
      relation: 'Self (Mother & Caretaker)',
      gender: 'Female',
      dob: '1989-04-12',
      bloodGroup: 'O+',
      genotype: 'AS',
      chronicConditions: ['Mild Asthma'],
      allergies: ['Penicillin'],
      avatarBg: '#047857',
      isPregnant: false,
      pregnancyStageWeeks: null,
      edd: null,
    },
    {
      id: 'mem_2',
      name: 'Ibrahim Bello',
      relation: 'Spouse',
      gender: 'Male',
      dob: '1985-08-22',
      bloodGroup: 'A+',
      genotype: 'AA',
      chronicConditions: ['Hypertension'],
      allergies: ['Sulfa drugs'],
      avatarBg: '#3B82F6',
      isPregnant: false,
    },
    {
      id: 'mem_3',
      name: 'Zainab Bello',
      relation: 'Daughter (Infant)',
      gender: 'Female',
      dob: '2026-03-10',
      bloodGroup: 'O+',
      genotype: 'AA',
      chronicConditions: [],
      allergies: ['None'],
      avatarBg: '#EC4899',
      isPregnant: false,
      vaccinesDue: [
        { id: 'vac_1', name: 'BCG & OPV 0', dueDate: '2026-03-12', completed: true, completedDate: '2026-03-12', batch: 'SER-8910' },
        { id: 'vac_2', name: 'Penta 1, PCV 1, Rota 1', dueDate: '2026-04-22', completed: true, completedDate: '2026-04-24', batch: 'GLX-2041' },
        { id: 'vac_3', name: 'Penta 2, PCV 2, Rota 2', dueDate: '2026-06-05', completed: true, completedDate: '2026-06-08', batch: 'GLX-3112' },
        { id: 'vac_4', name: 'Penta 3 / Polio 3 / PCV 3', dueDate: '2026-10-04', completed: false, notes: 'Critical visit for 14-week EPI schedule' },
        { id: 'vac_5', name: 'Vitamin A (1st Dose)', dueDate: '2026-11-10', completed: false, notes: 'Prevents childhood blindness' },
        { id: 'vac_6', name: 'Measles 1 & Yellow Fever', dueDate: '2026-12-10', completed: false, notes: '9 months milestone clinic day' },
      ],
      growthRecords: [
        { id: 'gw_1', date: '2026-03-10', ageMonths: 0, weightKg: 3.3, muacColor: 'Green', muacMm: 115, notes: 'Birth weight normal' },
        { id: 'gw_2', date: '2026-05-15', ageMonths: 2, weightKg: 5.2, muacColor: 'Green', muacMm: 128, notes: 'Exclusive breastfeeding' },
        { id: 'gw_3', date: '2026-07-20', ageMonths: 4, weightKg: 6.8, muacColor: 'Green', muacMm: 135, notes: 'Growth on 50th percentile WHO curve' },
        { id: 'gw_4', date: '2026-09-18', ageMonths: 6, weightKg: 7.6, muacColor: 'Green', muacMm: 140, notes: 'Complimentary feeding started' },
      ]
    },
    {
      id: 'mem_4',
      name: 'Mama Fatima',
      relation: 'Mother-in-law (Elder)',
      gender: 'Female',
      dob: '1958-11-04',
      bloodGroup: 'B+',
      genotype: 'AS',
      chronicConditions: ['Type 2 Diabetes', 'Hypertension'],
      allergies: ['Ibuprofen', 'Aspirin'],
      avatarBg: '#8B5CF6',
      isPregnant: false,
      regimen: [
        { name: 'Metformin', dosage: '500mg bd (twice daily after meals)', supplyRemainingDays: 14 },
        { name: 'Amlodipine', dosage: '5mg nocte (nightly)', supplyRemainingDays: 3 }
      ]
    },
  ],
  records: [
    {
      id: 'rec_101',
      memberId: 'mem_4',
      type: 'Prescription',
      category: 'Medication',
      provider: 'St. Nicholas Outpost, Victoria Island',
      date: '2026-09-21',
      details: 'Metformin 500mg bd (x30 days), Amlodipine 5mg nocte (x30 days). Salt reduction counseling given.',
      cost: 4200,
      verified: true,
      voiceNote: 'Doctor recommended checking fasting blood glucose in 2 weeks at local chemist.',
      confidence: 96,
    },
    {
      id: 'rec_102',
      memberId: 'mem_3',
      type: 'Immunization',
      category: 'Hospital Visits',
      provider: 'Iru Comprehensive Health Post',
      date: '2026-07-15',
      details: 'Penta 2, Rota 2, PCV 2 administered. Paracetamol drops given for low-grade fever.',
      cost: 0,
      verified: true,
      confidence: 98,
    },
    {
      id: 'rec_103',
      memberId: 'mem_2',
      type: 'Lab Test',
      category: 'Lab Tests',
      provider: 'Roadside Chemist Rapid Check',
      date: '2026-08-02',
      details: 'RDT Malaria: Positive (+). Prescribed Artemether Lumefantrine (Coartem) 80/480mg bd x 3 days.',
      cost: 2800,
      verified: false,
      confidence: 88,
    },
    {
      id: 'rec_104',
      memberId: 'mem_1',
      type: 'Receipt',
      category: 'Medication',
      provider: 'MedPlus Pharmacy & Health Store',
      date: '2026-08-25',
      details: 'Salbutamol inhaler 100mcg (1 canister) + Multivitamins with Zinc',
      cost: 3600,
      verified: true,
      confidence: 94,
    },
    {
      id: 'rec_105',
      memberId: 'mem_4',
      type: 'Lab Test',
      category: 'Lab Tests',
      provider: 'General Hospital Blood Services',
      date: '2026-09-02',
      details: 'HbA1c: 6.8%. Fasting Blood Sugar: 118 mg/dL. Blood pressure 138/86 mmHg.',
      cost: 5500,
      verified: true,
      confidence: 92,
    },
    {
      id: 'rec_106',
      memberId: 'mem_2',
      type: 'Prescription',
      category: 'Medication',
      provider: 'Adeyemi Chemist & Clinic',
      date: '2026-09-12',
      details: 'Lisinopril 10mg daily morning + Hydrochlorothiazide 12.5mg daily.',
      cost: 3100,
      verified: true,
      confidence: 91,
    }
  ],
};
