export const INITIAL_HOUSEHOLD = {
  id: 'fam_8b5a7a72',
  familyId: '8b5a7a72-7f3e-4d43-9821-6bc2299d4531',
  name: 'Adeyemi Family Health Circle',
  head: 'Femi Adeyemi',
  headRole: 'Primary Caretaker (G1)',
  currency: '₦',
  language: 'en', // 'en', 'pcm' (Pidgin), 'yo' (Yoruba), 'ha' (Hausa), 'ig' (Igbo)
  lastSyncTime: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  emergencyPhone: '+234 802 334 1122',
  clinicAnchor: 'General Hospital Ikeja & Iru PHC',
  completenessScore: 88,
  pendingAlerts: [
    { id: 'alt_1', memberId: 'mem_tunde', type: 'VACCINE_OVERDUE', text: '1 Vaccine Overdue: Pentavalent 3rd Dose for Tunde (14-week EPI schedule)', urgent: true },
    { id: 'alt_2', memberId: 'mem_baba', type: 'BP_UNCHECKED', text: '1 BP Log Due: Baba Adeyemi weekly blood pressure check', urgent: false },
  ],
  members: [
    {
      id: 'mem_baba',
      firstName: 'Babatunde',
      lastName: 'Adeyemi',
      name: 'Baba Adeyemi',
      generation: 'G0',
      generationLabel: 'Grandparent (G0)',
      relation: 'Father / Grandparent',
      gender: 'Male',
      dob: '1954-06-14',
      bloodGroup: 'O+',
      genotype: 'AS',
      chronicConditions: ['Essential Hypertension (Grade 1)', 'Mild Osteoarthritis'],
      allergies: ['Penicillin', 'Cephalosporins'],
      resuscitationOrder: 'Full Code (CPR / Intubation)',
      avatarBg: '#C85A32',
      statusNote: 'BP Watch',
      fatherId: null,
      motherId: null,
      primaryPhone: '+234 803 111 2233',
      regimen: [
        { name: 'Amlodipine', dosage: '5mg daily (nocte)', supplyRemainingDays: 6 },
        { name: 'Losartan Potassium', dosage: '50mg daily (morning)', supplyRemainingDays: 14 }
      ]
    },
    {
      id: 'mem_iya',
      firstName: 'Folashade',
      lastName: 'Adeyemi',
      name: 'Iya Adeyemi',
      generation: 'G0',
      generationLabel: 'Grandparent (G0)',
      relation: 'Mother / Grandparent',
      gender: 'Female',
      dob: '1958-11-20',
      bloodGroup: 'B+',
      genotype: 'AA',
      chronicConditions: ['None'],
      allergies: ['None declared'],
      resuscitationOrder: 'Full Code (CPR / Intubation)',
      avatarBg: '#1E4D38',
      statusNote: 'Normal',
      fatherId: null,
      motherId: null,
      primaryPhone: '+234 803 222 3344',
      regimen: []
    },
    {
      id: 'mem_femi',
      firstName: 'Femi',
      lastName: 'Adeyemi',
      name: 'Femi Adeyemi',
      generation: 'G1',
      generationLabel: 'Parent / Self (G1)',
      relation: 'Self (Primary Caretaker)',
      gender: 'Male',
      dob: '1984-04-18',
      bloodGroup: 'O+',
      genotype: 'AA',
      chronicConditions: ['None'],
      allergies: ['Penicillin'],
      resuscitationOrder: 'Full Code (CPR / Intubation)',
      avatarBg: '#1B2A4A',
      statusNote: 'Primary Account Owner',
      fatherId: 'mem_baba',
      motherId: 'mem_iya',
      primaryPhone: '+234 803 998 0011',
      regimen: []
    },
    {
      id: 'mem_sade',
      firstName: 'Sade',
      lastName: 'Adeyemi',
      name: 'Sade Adeyemi',
      generation: 'G1',
      generationLabel: 'Parent / Spouse (G1)',
      relation: 'Spouse (Mother)',
      gender: 'Female',
      dob: '1988-09-12',
      bloodGroup: 'A+',
      genotype: 'AS',
      chronicConditions: ['Gestational BP history'],
      allergies: ['Sulfa drugs'],
      resuscitationOrder: 'Full Code',
      avatarBg: '#D9822B',
      statusNote: 'Emergency Contact',
      fatherId: null,
      motherId: null,
      primaryPhone: '+234 802 334 1122',
      regimen: [
        { name: 'Prenatal Multivitamin with Iron & Folate', dosage: '1 tablet daily', supplyRemainingDays: 20 }
      ]
    },
    {
      id: 'mem_tunde',
      firstName: 'Babatunde Jr.',
      lastName: 'Adeyemi',
      name: 'Tunde Adeyemi',
      generation: 'G2',
      generationLabel: 'Child (G2)',
      relation: 'Son (Infant)',
      gender: 'Male',
      dob: '2026-03-10',
      bloodGroup: 'O+',
      genotype: 'AS',
      chronicConditions: ['Sickle Cell Trait (Carrier)'],
      allergies: ['None declared'],
      resuscitationOrder: 'Full Code (Pediatric)',
      avatarBg: '#C85A32',
      statusNote: 'Vaccine Due',
      fatherId: 'mem_femi',
      motherId: 'mem_sade',
      vaccinesDue: [
        { id: 'vac_1', name: 'BCG & OPV 0 (At Birth)', dueDate: '2026-03-12', completed: true, completedDate: '2026-03-12', batch: 'EPI-NG-8891', issuer: 'General Hospital Ikeja' },
        { id: 'vac_2', name: 'Penta 1, PCV 1, Rota 1 (6 Weeks)', dueDate: '2026-04-22', completed: true, completedDate: '2026-04-24', batch: 'GLX-2026-04', issuer: 'Iru Comprehensive PHC' },
        { id: 'vac_3', name: 'Penta 2, PCV 2, Rota 2 (10 Weeks)', dueDate: '2026-06-05', completed: true, completedDate: '2026-06-08', batch: 'GLX-2026-06', issuer: 'Iru Comprehensive PHC' },
        { id: 'vac_4', name: 'Penta 3, PCV 3, IPV (14 Weeks)', dueDate: '2026-10-01', completed: false, notes: 'CRITICAL OVERDUE: Pentavalent 3rd dose protects against Diphtheria, Pertussis, Tetanus, Hep B & Hib.' },
        { id: 'vac_5', name: 'Measles 1 & Yellow Fever (9 Months)', dueDate: '2026-12-10', completed: false, notes: 'Milestone protection against endemic measles outbreaks.' }
      ]
    },
    {
      id: 'mem_kehinde',
      firstName: 'Kehinde',
      lastName: 'Adeyemi',
      name: 'Kehinde Adeyemi',
      generation: 'G2',
      generationLabel: 'Child (G2)',
      relation: 'Daughter (Toddler)',
      gender: 'Female',
      dob: '2024-07-15',
      bloodGroup: 'O+',
      genotype: 'AA',
      chronicConditions: [],
      allergies: ['None declared'],
      resuscitationOrder: 'Full Code (Pediatric)',
      avatarBg: '#1E4D38',
      statusNote: 'Normal',
      fatherId: 'mem_femi',
      motherId: 'mem_sade',
      vaccinesDue: [
        { id: 'vac_k1', name: 'Full Routine WHO EPI Series (0-9m)', dueDate: '2025-04-15', completed: true, completedDate: '2025-04-15', batch: 'EPI-ALL-COMPLETED', issuer: 'General Hospital Ikeja' },
        { id: 'vac_k2', name: 'Vitamin A (18 Months Boost)', dueDate: '2026-01-15', completed: true, completedDate: '2026-01-18', batch: 'VITA-2026-01', issuer: 'Iru PHC' }
      ]
    }
  ],

  // Dual-Tier Health Records (Section 1.1 FR-03 & Section 3.1)
  records: [
    {
      id: 'rec_off_01',
      memberId: 'mem_tunde',
      provenance: 'OFFICIAL_VERIFIED', // OFFICIAL_VERIFIED | SELF_REPORTED
      category: 'VACCINATION',
      title: 'Pentavalent 2nd Dose (EPI Milestone)',
      recordedDate: '2026-06-08T09:30:00Z',
      issuerName: 'General Hospital Ikeja (EPI Unit)',
      issuerLicense: 'LSMOH/REG/2026/0491',
      attestationSignature: 'ed25519_sig_9f8a7b6c5d4e3f2a1b0c9e8d7c6b5a4f3e2d1c0b',
      documentSha256: 'a1b2c3d4e5f67a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
      details: 'Pentavalent (DTP-HepB-Hib) Dose 2 + Oral Polio Vaccine (OPV 2) + Rota 2. Batch #GLX-2026-06. Child tolerated with minimal swelling. Next dose due 14 weeks.',
      vitalMetrics: { temperature: '36.8°C', weight: '6.4 kg', site: 'Left anterolateral thigh' },
      verifiedSeal: true,
      hasEncryptedPdf: true
    },
    {
      id: 'rec_self_01',
      memberId: 'mem_baba',
      provenance: 'SELF_REPORTED',
      category: 'VITALS_LOG',
      title: 'Morning Blood Pressure & Heart Rate Log',
      recordedDate: '2026-10-02T07:15:00Z',
      issuerName: 'Logged by Femi (Self) via Omron M3 Monitor',
      issuerLicense: null,
      attestationSignature: null,
      documentSha256: null,
      details: 'Systolic: 142 mmHg | Diastolic: 88 mmHg (Elevated Stage 1). Pulse: 74 bpm. Note: Baba complained of mild occipital headache on waking. Took Losartan 50mg with water.',
      vitalMetrics: { systolic: 142, diastolic: 88, heartRate: 74, device: 'Omron Digital Arm Monitor' },
      verifiedSeal: false,
      hasEncryptedPdf: false
    },
    {
      id: 'rec_off_02',
      memberId: 'mem_femi',
      provenance: 'OFFICIAL_VERIFIED',
      category: 'LAB_RESULT',
      title: 'Comprehensive Metabolic Panel & Lipid Profile',
      recordedDate: '2026-09-15T11:00:00Z',
      issuerName: 'Synlab Lagos Diagnostic Reference Center',
      issuerLicense: 'MLSCN/LAB/2025/1190',
      attestationSignature: 'ed25519_sig_4e2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b',
      documentSha256: 'f8e7d6c5b4a39281706f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b',
      details: 'Total Cholesterol: 182 mg/dL (Desirable). Fasting Blood Glucose: 94 mg/dL. Creatinine: 0.9 mg/dL. eGFR: >90 mL/min/1.73m². All renal and hepatic enzymes within normal biological limits.',
      vitalMetrics: { glucose: '94 mg/dL', totalCholesterol: '182 mg/dL', eGFR: '>90' },
      verifiedSeal: true,
      hasEncryptedPdf: true
    },
    {
      id: 'rec_self_02',
      memberId: 'mem_baba',
      provenance: 'SELF_REPORTED',
      category: 'VITALS_LOG',
      title: 'Fasting Blood Sugar Log',
      recordedDate: '2026-09-28T06:45:00Z',
      issuerName: 'Patient Self-Check via Accu-Chek Guide',
      issuerLicense: null,
      attestationSignature: null,
      documentSha256: null,
      details: 'Fasting Blood Glucose: 114 mg/dL (Impaired fasting glucose / Pre-diabetes range). Baba had late yam dinner previous evening. Advised carbohydrate pacing.',
      vitalMetrics: { bloodSugar: '114 mg/dL', state: 'Fasting (10 hours)' },
      verifiedSeal: false,
      hasEncryptedPdf: false
    },
    {
      id: 'rec_off_03',
      memberId: 'mem_sade',
      provenance: 'OFFICIAL_VERIFIED',
      category: 'CLINICAL_ENCOUNTER',
      title: 'Cardiology Attestation & 12-Lead ECG Review',
      recordedDate: '2026-08-20T14:30:00Z',
      issuerName: 'First Cardiology Consultants, Ikoyi',
      issuerLicense: 'MDCN/HOSP/2024/0088',
      attestationSignature: 'ed25519_sig_7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b',
      documentSha256: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
      details: 'Attending: Dr. Babajide (Consultant Cardiologist). Normal sinus rhythm, rate 72 bpm. PR interval 156 ms, QRS 88 ms. No signs of left ventricular hypertrophy. Continue low-sodium diet.',
      vitalMetrics: { bloodPressure: '124/82 mmHg', heartRate: '72 bpm', ecgStatus: 'Normal Sinus Rhythm' },
      verifiedSeal: true,
      hasEncryptedPdf: true
    },
    {
      id: 'rec_self_03',
      memberId: 'mem_tunde',
      provenance: 'SELF_REPORTED',
      category: 'VITALS_LOG',
      title: 'Post-Teething Body Temperature Log',
      recordedDate: '2026-09-20T19:00:00Z',
      issuerName: 'Logged by Sade (Mother) via Braun Digital Ear',
      issuerLicense: null,
      attestationSignature: null,
      documentSha256: null,
      details: 'Temperature: 37.8°C (Mild low-grade elevation). Teething lower incisor. Given tepid sponge bath and infant paracetamol 2.5ml. Settled to sleep comfortably.',
      vitalMetrics: { temperature: '37.8°C', symptom: 'Lower gum swelling' },
      verifiedSeal: false,
      hasEncryptedPdf: false
    }
  ],

  // Healthcare Facilities Directory (PostGIS Geospatial Engine - Section 6.4)
  facilities: [
    {
      id: 'fac_1',
      name: 'General Hospital Ikeja',
      type: 'HOSPITAL',
      typeLabel: 'State General Hospital & Trauma Outpost',
      distanceKm: 2.4,
      phone: '+234 803 998 0011',
      emergency24_7: true,
      hmoAccepted: ['NHIA', 'LASHMA', 'Hygeia HMO', 'AXA Mansard', 'Reliance HMO'],
      address: 'Obafemi Awolowo Way, Ikeja, Lagos',
      operatingHours: '24/7 Continuous Emergency Readiness'
    },
    {
      id: 'fac_2',
      name: 'First Cardiology Consultants',
      type: 'SPECIALIST_CLINIC',
      typeLabel: 'Tertiary Cardiovascular Outpost',
      distanceKm: 4.1,
      phone: '+234 802 334 1122',
      emergency24_7: true,
      hmoAccepted: ['AXA Mansard', 'Hygeia Platinum', 'Bupa Global', 'Cigna'],
      address: 'Thompson Avenue, Ikoyi, Lagos',
      operatingHours: '24/7 ICU & Cardiac Emergency'
    },
    {
      id: 'fac_3',
      name: 'Iru Comprehensive Primary Health Post',
      type: 'PHC',
      typeLabel: 'Primary Health Care Board (EPI & MCH Hub)',
      distanceKm: 1.2,
      phone: '+234 809 111 4455',
      emergency24_7: false,
      hmoAccepted: ['NHIA (Free Infant EPI)', 'LASHMA Basic', 'Direct Community Pass'],
      address: 'Victoria Island Community Road, Lagos',
      operatingHours: 'Mon - Fri: 8:00 AM - 6:00 PM (Emergency Call On)'
    },
    {
      id: 'fac_4',
      name: 'MedPlus 24/7 Pharmacy & Triage Point',
      type: 'PHARMACY',
      typeLabel: 'Licensed Community Chemist & First Aid',
      distanceKm: 3.8,
      phone: '+234 805 777 8899',
      emergency24_7: true,
      hmoAccepted: ['Direct Pay', 'Reliance HMO', 'Avon HMO', 'Clearline'],
      address: 'Admiralty Way, Lekki Phase 1, Lagos',
      operatingHours: 'Open 24 Hours / 7 Days'
    },
    {
      id: 'fac_5',
      name: 'Synlab Reference Diagnostic Center',
      type: 'LABORATORY',
      typeLabel: 'Accredited ISO-15189 Clinical Pathology',
      distanceKm: 5.2,
      phone: '+234 803 444 9911',
      emergency24_7: false,
      hmoAccepted: ['All Major HMO Networks', 'Ed25519 Direct Attestation'],
      address: 'Adeola Odeku Street, Victoria Island, Lagos',
      operatingHours: 'Mon - Sat: 7:00 AM - 8:00 PM'
    }
  ]
};

// Vernacular Multilingual Translations & Colloquial Slang Mapping (FR-08)
export const VERNACULAR_TRANSLATIONS = {
  en: {
    title: 'FamilyHealth',
    subtitle: 'African Family Health Platform',
    circleTab: 'Circle',
    timelineTab: 'Timeline',
    sosTab: 'SOS Emergency',
    lineageTitle: 'Multi-Generational Health Circle',
    completeness: 'Family Health Completeness Index',
    overdueVaccine: 'Vaccine Overdue',
    bpCheckDue: 'BP Check Due',
    emergencyStrip: 'EMERGENCY HEALTH PASS',
    showQr: 'SHOW QR PASS',
    officialSeal: 'OFFICIAL VERIFIED SEAL',
    selfReported: 'SELF-REPORTED ENTRY',
    transferSelected: 'Transfer Selected',
    generatePin: 'Generate Doctor PIN',
    knowBeforeYouGo: 'Know Before You Go — Triage',
    nearbyFacilities: 'Care Discovery & Verified Facilities',
    speedDial: 'SPEED DIAL',
    slangMapping: {
      'my eye dey turn me': 'Vertigo / Presyncope (Dizziness)',
      'body dey hot well well': 'High-Grade Febrile Convulsion Risk (High Fever)',
      'belly dey bite me': 'Severe Abdominal Cramps / Acute Gastric Distress',
      'breathe dey hard me': 'Acute Dyspnea / Respiratory Distress'
    }
  },
  pcm: {
    title: 'FamilyHealth',
    subtitle: 'African Family Health Platform',
    circleTab: 'Circle',
    timelineTab: 'Timeline',
    sosTab: 'SOS Emergency',
    lineageTitle: 'Full Family Health Lineage (G0 - G2)',
    completeness: 'Family Health Completeness Meter',
    overdueVaccine: 'Vaccine Wey Don Late',
    bpCheckDue: 'BP Wey Baba Suppose Check',
    emergencyStrip: 'CRITICAL EMERGENCY HEALTH PASS',
    showQr: 'OPEN OFFLINE QR',
    officialSeal: 'GOVERNMENT / HOSPITAL VERIFIED RECORD',
    selfReported: 'PERSON LOG AM FOR HOUSE',
    transferSelected: 'Share Give Doctor',
    generatePin: 'Create 4-Digit Doctor PIN',
    knowBeforeYouGo: 'Check Before You Waka Go Clinic',
    nearbyFacilities: 'Hospitals & Chemist Wey Dey Near You',
    speedDial: 'CALL SHARP SHARP',
    slangMapping: {
      'my eye dey turn me': 'Vertigo / Head Dey Spin',
      'body dey hot well well': 'Serious High Fever (Check Malaria)',
      'belly dey bite me': 'Strong Stomach Pain',
      'breathe dey hard me': 'Chest Tight / Hard To Breathe'
    }
  },
  yo: {
    title: 'FamilyHealth',
    subtitle: 'Èrò Ìlera Ìdílé Áfíríkà',
    circleTab: 'Ẹ̀yà Ìdílé',
    timelineTab: 'Àkọsílẹ̀',
    sosTab: 'Pàjáwìrì (SOS)',
    lineageTitle: 'Àkọsílẹ̀ Ìran Ìdílé Pátápátá',
    completeness: 'Ìwọ̀n Pípé Ìlera Ìdílé',
    overdueVaccine: 'Àjẹsára Tó Ti Kọjá Àkókò',
    bpCheckDue: 'Ìwọ̀n Ẹ̀jẹ̀ Tó Yẹ Kí Baba Wò',
    emergencyStrip: 'PÁSÌ ÌLERA PÀJÁWÌRÌ',
    showQr: 'ṢÍ KÒÒDÙ QR',
    officialSeal: 'ÀKỌSÍLẸ̀ TÍ ILÉ-ÌWÒSÀN FỌWỌ́ SÍ',
    selfReported: 'ÀKỌSÍLẸ̀ TÍ AFẸNILỌ́LÁ ṢE FÚNRA RẸ̀',
    transferSelected: 'Pín Pẹ̀lú Dókítà',
    generatePin: 'Ṣẹ̀dá Nọ́ḿbà Àbò Dókítà',
    knowBeforeYouGo: 'Mọ̀ Kí O Tó Lọ — Ìtọ́sọ́nà Ìwòsàn',
    nearbyFacilities: 'Ilé-Ìwòsàn àti Ilé Oògùn Tí Ó Wà Nítòsí',
    speedDial: 'PÈ NÍ KIAKIA',
    slangMapping: {
      'my eye dey turn me': 'Ojú ńyí mi / Dizziness',
      'body dey hot well well': 'Ara ńgbóná púpọ̀ / High Fever',
      'belly dey bite me': 'Inú ńrun mi líle / Abdominal Pain',
      'breathe dey hard me': 'Èémí ńsọ mi / Shortness of Breath'
    }
  },
  ha: {
    title: 'FamilyHealth',
    subtitle: 'Dandalin Lafiyar Iyali na Afirka',
    circleTab: 'Iyali',
    timelineTab: 'Tarihin Lafiya',
    sosTab: 'Gaggawa (SOS)',
    lineageTitle: 'Dukkan Tarihin Zuri\'ar Iyali',
    completeness: 'Mizanin Cikar Kulawar Lafiya',
    overdueVaccine: 'Allurar Rigakafin Da Ta Wuce Lokaci',
    bpCheckDue: 'Auna Hawan Jini Na Baba',
    emergencyStrip: 'KASAR GAGGAWA NA LAFIYA',
    showQr: 'BUDE KODIN QR',
    officialSeal: 'SHAIDAR ASIBITI MAI INGANCI',
    selfReported: 'BAYANAN DA AKA RUBUTA A GIDA',
    transferSelected: 'Tura Wa Likita',
    generatePin: 'Kirkiri Lambar Sirri Ta Likita',
    knowBeforeYouGo: 'San Kafin Ka Tafi — Neman Magani',
    nearbyFacilities: 'Asibitoci Da Kantunan Magani Na Kusa',
    speedDial: 'KIRA DA SAURI',
    slangMapping: {
      'my eye dey turn me': 'Diddigi / Jiri (Dizziness)',
      'body dey hot well well': 'Zazzabi Mai Zafi (High Fever)',
      'belly dey bite me': 'Ciwon Ciki Mai Tsanani (Abdominal Cramps)',
      'breathe dey hard me': 'Numfashi Mai Wahala (Dyspnea)'
    }
  },
  ig: {
    title: 'FamilyHealth',
    subtitle: 'Usoro Nlekọta Ahụike Ezinụlọ Africa',
    circleTab: 'Ezinụlọ',
    timelineTab: 'Akụkọ Ahụike',
    sosTab: 'Mberede (SOS)',
    lineageTitle: 'Mkpụrụ Ezinụlọ Nile',
    completeness: 'Ọkwa Zuru Ezu nke Ahụike',
    overdueVaccine: 'Ọgwụ Mgbochi Na-agwụbeghị',
    bpCheckDue: 'Nleba Ọbara Mgbali Baba',
    emergencyStrip: 'PASS MBEREDE AHỤIKE',
    showQr: 'MEPEE QR OFFLINE',
    officialSeal: 'NDEKỌ ỤLỌỌGWỤ KWADORO',
    selfReported: 'NDEKỌ NDỊ MMADỤ DEERE N\'ỤLỌ',
    transferSelected: 'Kekọrịta Dọkịta',
    generatePin: 'Mepụta PIN Nchebe Dọkịta',
    knowBeforeYouGo: 'Mara Tupu I Gawa — Ntuziaka Ọgwụgwọ',
    nearbyFacilities: 'Ụlọ Ọgwụ na Ebe Ọgwụ Dị Nso',
    speedDial: 'KPOO N\'ỌSỌ',
    slangMapping: {
      'my eye dey turn me': 'Anya ịtụgharị / Dizziness',
      'body dey hot well well': 'Ahụ ọkụ dị ukwuu / High Fever',
      'belly dey bite me': 'Afọ mgbu siri ike / Abdominal Pain',
      'breathe dey hard me': 'Ikuru ume na-esiri ike / Dyspnea'
    }
  }
};
